var profile = "https://avatars.githubusercontent.com/u/86506519?v=4";

List categories = [
  {"name": "All", "icon": "assets/icons/pet-border.svg"},
  {"name": "Dog", "icon": "assets/icons/dog.svg"},
  {"name": "Cat", "icon": "assets/icons/cat.svg"},
  {"name": "Parrot", "icon": "assets/icons/parrot.svg"},
  {"name": "Rabbit", "icon": "assets/icons/rabbit.svg"},
  {"name": "Fish", "icon": "assets/icons/fish.svg"},
  {"name": "Turtle", "icon": "assets/icons/turtle.svg"},
];

List pets = [
  {
    "image":
        "https://images.unsplash.com/photo-1583511655826-05700d52f4d9?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "name": "Cheero",
    "location": "Siem Reap, Cambodia",
    "is_favorited": true,
    "description":
        "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    "rate": 4.5,
    "id": "pid001",
    "price": "\$1,250",
    "owner_name": "Sangvaleap",
    "owner_photo": profile,
    "sex": "Male",
    "age": "5 Months",
    "color": "Brown",
    "album": [
      "https://images.unsplash.com/photo-1558788353-f76d92427f16??ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1541364983171-a8ba01e95cfc?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1583511655826-05700d52f4d9?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1591768575198-88dac53fbd0a?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    ]
  },
  {
    "image":
        "https://images.unsplash.com/photo-1591768575198-88dac53fbd0a?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "name": "Bossy",
    "location": "Phnom Penh, Cambodia",
    "is_favorited": false,
    "description":
        "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    "rate": 4.5,
    "id": "pid001",
    "price": "\$1,250",
    "owner_name": "Sangvaleap",
    "owner_photo": profile,
    "sex": "Male",
    "age": "5 Months",
    "color": "Brown",
    "album": [
      "https://images.unsplash.com/photo-1541364983171-a8ba01e95cfc?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1583511655826-05700d52f4d9?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1591768575198-88dac53fbd0a?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    ]
  },
  {
    "image":
        "https://images.unsplash.com/photo-1541364983171-a8ba01e95cfc?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "name": "Maxi",
    "location": "Battambang, Cambodia",
    "is_favorited": false,
    "description":
        "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    "rate": 4.5,
    "id": "pid001",
    "price": "\$1,250",
    "owner_name": "Sangvaleap",
    "owner_photo": profile,
    "sex": "Male",
    "age": "5 Months",
    "color": "Brown",
    "album": [
      "https://images.unsplash.com/photo-1541364983171-a8ba01e95cfc?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1583511655826-05700d52f4d9?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1591768575198-88dac53fbd0a?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    ]
  },
  {
    "image":
        "https://images.unsplash.com/photo-1588269845464-8993565cac3a?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "name": "Coca",
    "location": "Phnom Penh, Cambodia",
    "is_favorited": false,
    "description":
        "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    "rate": 4.5,
    "id": "pid001",
    "price": "\$1,250",
    "owner_name": "Sangvaleap",
    "owner_photo": profile,
    "sex": "Male",
    "age": "5 Months",
    "color": "Brown",
    "album": [
      "https://images.unsplash.com/photo-1541364983171-a8ba01e95cfc?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1583511655826-05700d52f4d9?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1591768575198-88dac53fbd0a?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    ]
  },
  {
    "image":
        "https://images.unsplash.com/photo-1556227702-d1e4e7b5c232?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "name": "Lazoo",
    "location": "Phnom Penh, Cambodia",
    "is_favorited": true,
    "description":
        "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    "rate": 4.5,
    "id": "pid001",
    "price": "\$1,250",
    "owner_name": "Sangvaleap",
    "owner_photo": profile,
    "sex": "Male",
    "age": "5 Months",
    "color": "Brown",
    "album": [
      "https://images.unsplash.com/photo-1541364983171-a8ba01e95cfc?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1583511655826-05700d52f4d9?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1591768575198-88dac53fbd0a?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    ]
  },
  {
    "image":
        "https://images.unsplash.com/photo-1598875184988-5e67b1a874b8?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "name": "Meido",
    "location": "Phnom Penh, Cambodia",
    "is_favorited": false,
    "description":
        "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    "rate": 4.5,
    "id": "pid001",
    "price": "\$1,250",
    "owner_name": "Sangvaleap",
    "owner_photo": profile,
    "sex": "Male",
    "age": "5 Months",
    "color": "Brown",
    "album": [
      "https://images.unsplash.com/photo-1541364983171-a8ba01e95cfc?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1583511655826-05700d52f4d9?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1591768575198-88dac53fbd0a?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    ]
  },
  {
    "image":
        "https://images.unsplash.com/photo-1587764379873-97837921fd44?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "name": "Koko",
    "location": "Phnom Penh, Cambodia",
    "is_favorited": false,
    "description":
        "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    "rate": 4.5,
    "id": "pid001",
    "price": "\$1,250",
    "owner_name": "Sangvaleap",
    "owner_photo": profile,
    "sex": "Male",
    "age": "5 Months",
    "color": "Brown",
    "album": [
      "https://images.unsplash.com/photo-1541364983171-a8ba01e95cfc?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1583511655826-05700d52f4d9?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1591768575198-88dac53fbd0a?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    ]
  },
  {
    "image":
        "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "name": "Roka",
    "location": "Phnom Penh, Cambodia",
    "is_favorited": false,
    "description":
        "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    "rate": 4.5,
    "id": "pid001",
    "price": "\$1,250",
    "owner_name": "Sangvaleap",
    "owner_photo": profile,
    "sex": "Male",
    "age": "5 Months",
    "color": "Brown",
    "album": [
      "https://images.unsplash.com/photo-1541364983171-a8ba01e95cfc?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1583511655826-05700d52f4d9?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1591768575198-88dac53fbd0a?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
      "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    ]
  },
];

var chats = [
  {
    "image":
        "https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjV8fHByb2ZpbGV8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "fname": "John",
    "lname": "Siphron",
    "name": "John Siphron",
    "skill": "Dermatologists",
    "last_text":
        "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document",
    "date": "1 min",
    "notify": 4,
  },
  {
    "image":
        "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTF8fHByb2ZpbGV8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "fname": "Corey",
    "lname": "Aminoff",
    "name": "Corey Aminoff",
    "skill": "Neurologists",
    "last_text":
        "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document",
    "date": "3 min",
    "notify": 2,
  },
  {
    "image":
        "https://images.unsplash.com/photo-1617069470302-9b5592c80f66?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8Z2lybHxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "fname": "Siriya",
    "lname": "Aminoff",
    "name": "Siriya Aminoff",
    "skill": "Neurologists",
    "last_text":
        "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document",
    "date": "1 hr",
    "notify": 1,
  },
  {
    "image":
        "https://images.unsplash.com/photo-1545167622-3a6ac756afa4?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTB8fHByb2ZpbGV8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "fname": "Rubin",
    "lname": "Joe",
    "name": "Rubin Joe",
    "skill": "Neurologists",
    "last_text":
        "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document",
    "date": "1 hr",
    "notify": 1,
  },
  {
    "image":
        "https://images.unsplash.com/photo-1564460576398-ef55d99548b2?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTZ8fHByb2ZpbGV8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "fname": "John",
    "lname": "",
    "name": "DentTerry Jew",
    "skill": "Dentist",
    "last_text":
        "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document",
    "date": "2 hrs",
    "notify": 0,
  },
  {
    "image":
        "https://images.unsplash.com/photo-1622253692010-333f2da6031d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=928&q=80",
    "fname": "John",
    "lname": "",
    "name": "Corey Aminoff",
    "skill": "Neurologists",
    "last_text":
        "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document",
    "date": "5 hrs",
    "notify": 0,
  },
];

Map<String, String> dogFoodMap = {
  'chihuahua': 'high-quality small breed dog food',
  'japanese spaniel': 'small breed dog food',
  'maltese dog': 'small breed dog food',
  'pekinese': 'small breed dog food',
  'shih tzu': 'small breed dog food',
  'blenheim spaniel': 'small breed dog food',
  'papillon': 'small breed dog food',
  'toy terrier': 'small breed dog food',
  'rhodesian ridgeback': 'large breed dog food',
  'afghan hound': 'large breed dog food',
  'basset': 'large breed dog food',
  'beagle': 'medium breed dog food',
  'bloodhound': 'large breed dog food',
  'bluetick': 'large breed dog food',
  'black and tan coonhound': 'large breed dog food',
  'walker hound': 'large breed dog food',
  'english foxhound': 'large breed dog food',
  'redbone': 'large breed dog food',
  'borzoi': 'large breed dog food',
  'irish wolfhound': 'large breed dog food',
  'italian greyhound': 'small breed dog food',
  'whippet': 'small breed dog food',
  'ibizan hound': 'medium breed dog food',
  'norwegian elkhound': 'medium breed dog food',
  'otterhound': 'large breed dog food',
  'saluki': 'medium breed dog food',
  'scottish deerhound': 'large breed dog food',
  'weimaraner': 'medium to large breed dog food',
  'staffordshire bullterrier': 'medium breed dog food',
  'american staffordshire terrier': 'medium breed dog food',
  'bedlington terrier': 'medium breed dog food',
  'border terrier': 'small to medium breed dog food',
  'kerry blue terrier': 'medium breed dog food',
  'irish terrier': 'medium breed dog food',
  'norfolk terrier': 'small breed dog food',
  'norwich terrier': 'small breed dog food',
  'yorkshire terrier': 'small breed dog food',
  'wire haired fox terrier': 'medium breed dog food',
  'lakeland terrier': 'medium breed dog food',
  'sealyham terrier': 'medium breed dog food',
  'airedale': 'medium to large breed dog food',
  'cairn': 'small breed dog food',
  'australian terrier': 'small breed dog food',
  'dandie dinmont': 'small breed dog food',
  'boston bull': 'small breed dog food',
  'miniature schnauzer': 'small breed dog food',
  'giant schnauzer': 'large breed dog food',
  'standard schnauzer': 'medium breed dog food',
  'scotch terrier': 'medium breed dog food',
  'tibetan terrier': 'medium breed dog food',
  'silky terrier': 'small breed dog food',
  'soft coated wheaten terrier': 'medium breed dog food',
  'west highland white terrier': 'small breed dog food',
  'lhasa': 'small breed dog food',
  'flat coated retriever': 'medium to large breed dog food',
  'curly coated retriever': 'medium to large breed dog food',
  'golden retriever': 'large breed dog food',
  'labrador retriever': 'large breed dog food',
  'chesapeake bay retriever': 'large breed dog food',
  'german short haired pointer': 'medium to large breed dog food',
  'vizsla': 'medium to large breed dog food',
  'english setter': 'medium to large breed dog food',
  'irish setter': 'medium to large breed dog food',
  'gordon setter': 'medium to large breed dog food',
  'brittany spaniel': 'medium breed dog food',
  'clumber': 'large breed dog food',
  'english springer': 'medium to large breed dog food',
  'welsh springer spaniel': 'medium breed dog food',
  'cocker spaniel': 'medium breed dog food',
  'sussex spaniel': 'medium breed dog food',
  'irish water spaniel': 'medium breed dog food',
  'kuvasz': 'large breed dog food',
  'schipperke': 'small to medium breed dog food',
  'groenendael': 'medium to large breed dog food',
  'malinois': 'medium to large breed dog food',
  'briard': 'large breed dog food',
  'kelpie': 'medium to large breed dog food',
  'komondor': 'large breed dog food',
  'old english sheepdog': 'large breed dog food',
  'shetland sheepdog': 'small to medium breed dog food',
  'collie': 'medium to large breed dog food',
  'border collie': 'medium to large breed dog food',
  'bouvier des flandres': 'large breed dog food',
  'rottweiler': 'large breed dog food',
  'german shepherd': 'large breed dog food',
  'doberman': 'large breed dog food',
  'miniature pinscher': 'small breed dog food',
  'greater swiss mountain dog': 'large breed dog food',
  'bernese mountain dog': 'large breed dog food',
  'appenzeller': 'large breed dog food',
  'entlebucher': 'medium to large breed dog food',
  'boxer': 'medium to large breed dog food',
  'bull mastiff': 'large breed dog food',
  'tibetan mastiff': 'large breed dog food',
  'french bulldog': 'small breed dog food',
  'great dane': 'large breed dog food',
  'saint bernard': 'large breed dog food',
  'eskimo dog': 'medium breed dog food',
  'malamute': 'large breed dog food',
  'siberian husky': 'medium to large breed dog food',
  'affenpinscher': 'small breed dog food',
  'basenji': 'small breed dog food',
  'pug': 'small breed dog food',
  'leonberg': 'large breed dog food',
  'newfoundland': 'large breed dog food',
  'great pyrenees': 'large breed dog food',
  'samoyed': 'medium to large breed dog food',
  'pomeranian': 'small breed dog food',
  'chow': 'medium to large breed dog food',
  'keeshond': 'medium breed dog food',
  'brabancon griffon': 'small to medium breed dog food',
  'pembroke': 'medium to large breed dog food',
  'cardigan': 'medium to large breed dog food',
  'toy poodle': 'small breed dog food',
  'miniature poodle': 'small to medium breed dog food',
  'standard poodle': 'medium to large breed dog food',
  'mexican hairless': 'small to medium breed dog food',
  'dingo': 'wild game or a high-quality commercial dog food',
  'dhole': 'wild game or a high-quality commercial dog food',
  'african hunting dog': 'wild game or a high-quality commercial dog food',
};
